language: java
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled
branches:
  only:
  - master
  - dev
  - thymeleaf
install:
- true
notifications:
  slack:
    on_success: change
    on_failure: change
    slack: hellowood:3qHqpWCi2LQV4MsQYPsHJBK6
before_install:
- chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash) -t 92b3ad6b-92f7-49bb-94e7-ea233b860e47