codecov:
  notify:
    require_ci_to_pass: yes
  ci:
    - http://ali.hellowoodes.com.cn:8855      # add my custom jenkins server
    - !appveyor                               # ignore CI builds by AppVeyor
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no
  notify:
      slack:
        default:
          url: "https://hooks.slack.com/services/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"
          threshold: 1%
          only_pulls: false
          branches: null
          flags: null
          paths: null

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

